/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DBConnection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import oms.rmi.db.Conn;

/**
 *
 * @author Administrator
 */
public class DBConnection {

    public static int getNewPmi() {
        int nilai = 1;
        try {
            String sql = "SELECT pmi_i "
                    + "FROM autogenerated_pmi "
                    + "ORDER BY pmi_i DESC";
            PreparedStatement ps = Conn.MySQLConnect().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                nilai = rs.getInt("pmi_i");
                sql = "INSERT INTO autogenerated_pmi(pmi_i) "
                        + "VALUES(?)";
                PreparedStatement ps2 = Conn.MySQLConnect().prepareStatement(sql);
                ps2.setInt(1, nilai + 1);
                ps2.execute();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return nilai;
    }
    
}
